jobs:

# jobs for the dv pipeline from CI thru TEST environment


# manifest gen for VISUALIZER
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-img
      - IN: dv-img-opts  
      - TASK: managed

#/ manifest gen for VISUALIZER

# TEST deployment for VISUALIZER to Amazon ECS
  - name: dv-test-ecs
    type: deploy
    steps:
      - IN: dv-man
#      - IN: dv-params
      - IN: plus-lb
      - IN: env-test-ecs
      applyTo:
          - manifest: dv-man
            image: dv-img
            port: 0
      - TASK: managed

# / TEST deployment for VISUALIZER to Amazon ECS
